### ISSUE TITLE
Page not found only displayed at one level

### ISSUE THREAD

**Issue by yoanngueny** [cher-ami/router#32]
Example :
```js
{
    path: "/:rest",
    component: PageNotFound,
    name: EPage.NOT_FOUND,
  },
```

This route will only be triggered at the first level `/bad_route`.
But it will not be triggered at the second and others `/bad_route/another_bad_route`.

**Comment by willybrauner** [comment]
It's because `/bad_route/another_bad_route` do not match with your route definition. So like we said, the workaround is : 

```js
  {
    path: "/:rest",
    component: forwardRef((props, r) => <div className="NotFoundPage">Not Found</div>),
  },
  {
    path: "/:rest/:rest",
    component: forwardRef((props, r) => <div className="NotFoundPage">Not Found</div>),
  },
```

**Comment by yoanngueny** [comment]
I don't think this is a proper workaround.
All bad routes should redirect to not found.
For example, a user could write `/whatever/he/wants/to/write`.

**Comment by willybrauner** [comment]
Right, I gonna check it.
